version: '3'

volumes:
  postgres_data:
    driver: local

services:
    postgres:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: Keycloak123
 
      ports:
        - 5433:5432 
    auth:
      image: quay.io/keycloak/keycloak:latest
      #network_mode: host 
      ports:
        - "8185:8185"
      environment:
        - DB_VENDOR=POSTGRES
        - DB_ADDR=postgresql
        - DB_PORT=5432
        - DB_SCHEMA=public
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=Keycloak123

        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=password
      
      command: 
        - start-dev 
        - --http-port=8185
        - --import-realm
        
       # - --hostname-admin=/auth 
      volumes:
        - /Users/daveotengo/Desktop/git/docker/keycloak-final/howtodoinjava-realm.json:/opt/keycloak/data/import/howtodoinjava-realm.json
        #- /Users/daveotengo/Desktop/git/docker/keycloak-final/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      depends_on:
        - postgres
