server:
  port: 6062
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
spring:
  application:
    name:  DRIVER-SERVICE
  config:  
    import: "optional:configserver:http://localhost:9296"
  datasource:
    url: jdbc:postgresql://localhost:5432/driver-service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: rydex
    password: rydex456
    driver-class-name: org.postgresql.Driver
    

    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true

    hibernate:
      ddl-auto: update
      
      
management:
  tracing:
    sampling:
      probability: 1.0
        
    
#  zipkin:
#    base-url: http://127.0.0.1:9411/

