server:
  port: 8060
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
spring:
  application:
    name:  API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
        - id: DRIVER-SERVICE
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/driver/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DRIVER-SERVICE
#                fallbackuri: forward:/driverServiceFallBack

        - id: ADMINER-SERVICE
          uri: lb://ADMINER-SERVICE
          predicates:
            - Path=/adminers/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
        - id: RIDE-SERVICE
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/rides/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DRIVER-SERVICE
#                fallbackuri: forward:/driverServiceFallBack

        - id: PROVIDER-SERVICE
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/providers/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
        - id: SUPPORT-SERVICE
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/support/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DRIVER-SERVICE
#                fallbackuri: forward:/driverServiceFallBack

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DRIVER-SERVICE
#                fallbackuri: forward:/driverServiceFallBack
        - id: SCHEDULE-SERVICE
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/schedules/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack

  config:  
    import: "optional:configserver:http://localhost:9296"
 
      
      
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000



 