server:
  port: 6061
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
spring:
  application:
    name:  USER-SERVICE
  config:  
    import: "optional:configserver:http://localhost:9296"
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: rydex
    password: rydex456
    driver-class-name: org.postgresql.Driver

    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      
management:
  tracing:
    sampling:
      probability: 1.0
        
    
#  zipkin:
#    base-url: http://127.0.0.1:9411/